version: "3.6"
services:
  dbnode01:
    expose:
      - "9000-9004"
    ports:
      - "0.0.0.0:9000-9004:9000-9004"
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:2379-2380:2379-2380"
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    image: m3db_dbnode01:latest
networks:
  backend:
